FROM node:22-alpine

WORKDIR /app

RUN corepack enable

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile --prod

COPY server ./server

EXPOSE 3000 3001

CMD ["node", "--experimental-strip-types", "server/mock.ts"]

